force-app/main/default/objects/Bill__c/Bill__c.object-meta.xml
<CustomObject>
    <label>Bill</label>
    <nameField>
        <displayFormat>Bill-{0000}</displayFormat>
        <label>Bill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bill__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bills</relationshipLabel>
    <relationshipName>Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bill__c/fields/BillAmount__c.field-meta.xml
<CustomField>
    <fullName>BillAmount__c</fullName>
    <label>Bill Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PayPal__c/PayPal__c.object-meta.xml
<CustomObject>
    <label>PayPal</label>
    <nameField>
        <displayFormat>PayPal-{0000}</displayFormat>
        <label>PayPal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PayPal&#39;s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PayPal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PayPal&#39;s</relationshipLabel>
    <relationshipName>PayPal_s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PayByPayPal.cls
public without sharing class PayByPayPal implements PayStrategy{

    public Boolean pay(Bill__c bill) {
        List<PayPal__c> payPals = [SELECT Id, Amount__c FROM PayPal__c WHERE Account__c =: bill.Account__c];
        for(PayPal__c payPal: payPals){
            if(bill.BillAmount__c < payPal.Amount__c ){
                payPal.Amount__c = payPal.Amount__c - bill.BillAmount__c;
                update payPal;
                return true;
            }
        }
        return false;
    }
}