force-app/main/default/objects/Bill__c/Bill__c.object-meta.xml
<CustomObject>
    <label>Bill</label>
    <nameField>
        <displayFormat>Bill-{0000}</displayFormat>
        <label>Bill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bill__c/fields/BillAmount__c.field-meta.xml
<CustomField>
    <fullName>BillAmount__c</fullName>
    <label>Bill Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bill__c/fields/PayType__c.field-meta.xml
<CustomField>
    <fullName>PayType__c</fullName>
    <label>Pay Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PayPal</fullName>
            </value>
            <value>
                <fullName>CreditCard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bill__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>PaidByCreditCard</fullName>
                <label>Paid by Credit Card</label>
            </value>
            <value>
                <fullName>PaidByPayPal</fullName>
                <label>Paid by PayPal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BillTriggerHandler.cls
public with sharing class BillTriggerHandler extends TriggerHandler {

    public override void beforeInsert(){
        pay(Trigger.new);
    }

    public override void beforeUpdate(){
        pay(Trigger.new);
    }

    private void pay(List<Bill__c> records){
        for(Bill__c record : records){
            if(record.BillAmount__c != null
                    && record.PayType__c != null
                    && record.Status__c == 'Draft'){
                AdapterPayStrategy strategy;

                switch on record.PayType__c{
                    when 'PayPal'{
                        strategy = new AdapterPayByPayPal();
                    }
                    when 'CreditCard'{
                        strategy = new AdapterPayByCreditCard();
                    }
                }

                if(!strategy.fastPay(record)){
                    record.addError('You can not pay by ' + record.PayType__c);
                }
            }
        }
    }
}