force-app/main/default/objects/Bill__c/Bill__c.object-meta.xml
<CustomObject>
    <label>Bill</label>
    <nameField>
        <displayFormat>Bill-{0000}</displayFormat>
        <label>Bill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bill__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bills</relationshipLabel>
    <relationshipName>Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bill__c/fields/BillAmount__c.field-meta.xml
<CustomField>
    <fullName>BillAmount__c</fullName>
    <label>Bill Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CreditCard__c/CreditCard__c.object-meta.xml
<CustomObject>
    <label>Credit Card</label>
    <nameField>
        <displayFormat>CreditCard-{0000}</displayFormat>
        <label>CreditCard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditCard__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Cards</relationshipLabel>
    <relationshipName>Credit_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PayByCreditCard.cls
public without sharing class PayByCreditCard implements PayStrategy {

    public Boolean pay(Bill__c bill) {
        List<CreditCard__c> creditCards = [SELECT Id, Amount__c FROM CreditCard__c WHERE Account__c =: bill.Account__c];
        for(CreditCard__c card: creditCards){
            if(bill.BillAmount__c < card.Amount__c ){
                card.Amount__c = card.Amount__c - bill.BillAmount__c;
                update card;
                return true;
            }
        }
        return false;
    }
}