force-app/main/default/objects/PublisherMessages__c/PublisherMessages__c.object-meta.xml
<CustomObject>
    <label>PublisherMessages</label>
    <nameField>
        <displayFormat>Messeges-{0000}</displayFormat>
        <label>PublisherMessages Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PublisherMessages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PublisherMessages__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>PublisherMessages</relationshipLabel>
    <relationshipName>PublisherMessages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/Subscriber__c.object-meta.xml
<CustomObject>
    <label>Subscriber</label>
    <nameField>
        <label>Subscriber Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriberMessage__c/SubscriberMessage__c.object-meta.xml
<CustomObject>
    <label>SubscriberMessage</label>
    <nameField>
        <displayFormat>SubMes-{0000}</displayFormat>
        <label>SubscriberMessage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubscriberMessage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriberMessage__c/fields/PublisherMessages__c.field-meta.xml
<CustomField>
    <fullName>PublisherMessages__c</fullName>
    <label>PublisherMessages</label>
    <referenceTo>PublisherMessages__c</referenceTo>
    <relationshipLabel>SubscriberMessage</relationshipLabel>
    <relationshipName>SubscriberMessage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SubscriberMessage__c/fields/Subscriber__c.field-meta.xml
<CustomField>
    <fullName>Subscriber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscriber</label>
    <referenceTo>Subscriber__c</referenceTo>
    <relationshipLabel>SubscriberMessage</relationshipLabel>
    <relationshipName>SubscriberMessage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriberToPublisher__c/SubscriberToPublisher__c.object-meta.xml
<CustomObject>
    <label>Subscriber to publisher</label>
    <nameField>
        <displayFormat>SubToPub-{0000}</displayFormat>
        <label>Subscriber to publisher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriber to publisher</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SubscriberToPublisher__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Subscriber to publisher</relationshipLabel>
    <relationshipName>Subscriber_to_publisher</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SubscriberToPublisher__c/fields/Subscriber__c.field-meta.xml
<CustomField>
    <fullName>Subscriber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscriber</label>
    <referenceTo>Subscriber__c</referenceTo>
    <relationshipLabel>Subscriber to publisher</relationshipLabel>
    <relationshipName>Subscriber_to_publisher</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PublisherMessagesHandler.cls
public with sharing class PublisherMessagesHandler extends TriggerHandler {
    public override void afterInsert() {
        createSubscriberMessage(Trigger.new);
    }

    public override void afterUpdate() {

    }

    public override void afterDelete() {

    }


    private void createSubscriberMessage(List<PublisherMessages__c> records) {
        List<String> publisherIds = new List<String>();
        for (PublisherMessages__c record : records) {
            publisherIds.add(record.Publisher__c);
        }

        List<SubscriberToPublisher__c> subToPub = [
                SELECT id,
                        Publisher__c,
                        Subscriber__c
                FROM SubscriberToPublisher__c
                WHERE Publisher__c IN :publisherIds
        ];

        //create map all subscriber where key Publisher Id
        Map<String, List<String>> subscriberByPublisher = new Map<String, List<String>>();
        for (SubscriberToPublisher__c record : subToPub) {
            if (subscriberByPublisher.containsKey(record.Publisher__c)) {
                subscriberByPublisher.get(record.Publisher__c).add(record.Subscriber__c);
            } else {
                List<String> subscriberIds = new List<String>();
                subscriberIds.add(record.Subscriber__c);
                subscriberByPublisher.put(record.Publisher__c, subscriberIds);
            }
        }


        List<SubscriberMessage__c> subscriberMessages = new List<SubscriberMessage__c>();
        for (PublisherMessages__c record : records) {
            for (Id subscriberId : subscriberByPublisher.get(record.Publisher__c)) {
                subscriberMessages.add(
                        new SubscriberMessage__c(
                                PublisherMessages__c = record.Id,
                                Subscriber__c = subscriberId));
            }
        }

        insert subscriberMessages;
    }
}